# Generated by Django 5.0.2 on 2024-03-11 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_room_options_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
